# Generated by Django 3.1.3 on 2021-03-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('join_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('password', models.CharField(default='', max_length=50)),
                ('u_img', models.ImageField(default='', max_length=200, upload_to='Images_Data/')),
                ('u_files', models.FileField(default='', max_length=200, upload_to='Files_Data/')),
            ],
        ),
    ]
