# Generated by Django 3.1.3 on 2021-03-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='email',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='u_files',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='u_img',
        ),
        migrations.AddField(
            model_name='homepage',
            name='cpassword',
            field=models.CharField(default='', max_length=50),
        ),
    ]
