# Generated by Django 3.1.3 on 2021-03-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0002_auto_20210305_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cpassword',
            field=models.CharField(default='', max_length=100),
        ),
    ]
