# Generated by Django 3.1.3 on 2021-03-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0003_auto_20210305_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='join_time',
        ),
    ]
