# Generated by Django 3.1.5 on 2021-04-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0005_admin_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_reg',
            name='aphone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
